name: Elevation Test Site
favicon: null
layout_spectrum: 0.50963
typography_spectrum: 0.60847
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ff6600'
    - '#000000'
    - '#c9c9c9'
    - '#818181'
  brandStrength: 0.25
  lightness: 0.2868687668815255
  saturation: 0.9538089176639915
  rhythmicContrast: 0.75
purpose: []
