name: Elevation Test Site
favicon: null
layout_spectrum: 1
typography_spectrum: 0.60847
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ff6600'
    - '#000000'
    - '#c9c9c9'
    - '#818181'
  brandStrength: 0.1875
  lightness: 0.5
  saturation: 0.625
  rhythmicContrast: 1
purpose: []
